### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by hamster108** [yannponty/DeClone#2]
While running 'make DeClone' command, program returned an error:

<pre>src/DeClone-parsimony.cc:55:69: error: ‘computeMatrixParsimony’ was not declared in this scope
      return MIN(computeMatrixParsimony(tree1,tree2,true, adjacencies),
                                                                     ^
src/DeClone-parsimony.cc:42:34: note: in definition of macro ‘MIN’
 #define MIN(a,b,c,adj,g1,g2) min(a,b)
                                  ^
make: *** [src/DeClone-parsimony.o] Error1</pre>

---

Used gcc version 4.8.1 (Ubuntu 4.8.1-2ubuntu1~12.04)
g++  4.8.1

**Comment by yannponty** [comment]
Dear Hamster108,

Just rebuilt the master branch without any problem (g++/gcc 5.3.0 and python 2.7.9).
Do you have a recent python version installed and, if so, which version number?
Do you see a file 'OperationsList.hh' in the 'src' directory?

**Comment by hamster108** [comment]
Thank you for reply, yannponty!
My python version is 2.7.3 and the file 'OperationsList.hh' is seen, but I do not understand how to use it.

**Comment by ashokrajaraman** [comment]
Hello hamster108,

The file 'OperationsList.hh' is not meant to be manually modified; it is created during compilation. As of now, the other contributors to this project have tried to reproduce your error, but have unfortunately failed. Could you please try to compile it on another machine and check if it works?

**Comment by hamster108** [comment]
Hello ashokrajaraman,

We tried to compile it on Ubuntu 14.04 32-bit, with gcc version 4.8.4 and there was the same mistake. Then we tried to compile it on Ubuntu 14.04 64-bit with the same gcc version and everything was alright.
Thank you for assistance.
